# Generated by Django 4.2.3 on 2023-07-24 20:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dish", "0002_dish_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dish",
            name="price",
            field=models.PositiveIntegerField(),
        ),
    ]
