# Generated by Django 4.2.3 on 2023-07-24 20:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="total_amount",
            field=models.PositiveIntegerField(),
        ),
    ]
